### ISSUE TITLE
Result in CSV and Raw differs

### ISSUE THREAD

**Issue by JustinWonjaePark** [scanoss/quickscan#11]
I've been trying to test QuickScan v1.2.4
And I ran scan for some source code (https://github.com/fosslight/fosslight_source_scanner)

As result, when I downloaded CSV Results, there were 9 files listed, while Raw Results (.json) contain 7 files.

This is the .csv file I got, and I marked the missing files in .json file in red.

![image](https://user-images.githubusercontent.com/33045921/136500522-d8d7adb2-6c8d-4fc8-adec-9bde84d2ad70.png)

Result of scanoss.py(https://github.com/scanoss/scanoss.py) were same with the Raw Result.

Is there any reason that the .json files dosen't contain LICENSE files ?

**Comment by mscasso-scanoss** [comment]
Hi @JustinWonjaePark, Quickscan is deprecated and will be replaced for a new product in the next days. I'm going to let new know soon!
